feat: Updated CSPROJ version. #179944
audaciaconsulting/Audacia.Spreadsheets pull request #7
Opened 2024-10-23 14:56 UTC by charliebenjamin-audacia

…ted changelog to reflect past changes. #179944

| Action | Done? |
| --- | --- |
| CHANGELOG updated | ✔ |
| Code compiles and unit tests all pass locally | ✔ |
| Debug/console log code removed | ✔ |
| Commented out code removed | ✔ |
| Unit tests added/updated | ✔ |
| README updated | ✔ |
| Considered: <br /> - Performance <br /> - Security <br /> - Logging | ✔ |
| Licenses of any new/upgraded dependencies checked, with no copyleft dependencies introduced | ✔ |

2024-10-25 12:53 UTC, kieran-wilkinson-audacia approved these changes

2024-11-19 12:43 UTC, jackpercy-acl requested changes

2024-11-19 12:43 UTC, jackpercy-acl commented on src/Audacia.Spreadsheets/Audacia.Spreadsheets.csproj
> +    <Version>1.2.1</Version>
This should be `1.2.2` and AssemblyVersion can be removed

2024-11-20 13:33 UTC, richardb355 commented on src/Audacia.Spreadsheets/Audacia.Spreadsheets.csproj
> +    <Version>1.2.1</Version>
Good spot. Should be fixed.

2024-11-20 14:57 UTC, jackpercy-acl submitted a review, later dismissed

2024-11-21 11:23 UTC, jackpercy-acl approved these changes

2024-11-21 11:31 UTC, merged